name: Django CI

on:
  push:
    branches: [ main, '**']
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Building Docker Stack
      run: docker-compose -f local.yml build

    - name: Testing Django Application
      run: docker-compose -f local.yml run app sh -c "python manage.py test && flake8"